# Generated by Django 5.1.5 on 2025-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='embed_code',
        ),
        migrations.AddField(
            model_name='game',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
