# Generated by Django 5.1.5 on 2025-01-25 06:23

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_embed_code_game_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
